name: Hexo Auto Deploy

on:
  push:
    branches:
      - develop

env:
  GIT_USER: javerVip
  GIT_EMAIL: 1@javer.vip
  GIT_DEPLOY_BRANCH: output

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm install hexo-cli -g

      - name: Build Hexo
        run: |
          hexo clean
          hexo generate

      - name: Deploy to GitHub Pages
        env:
          DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          # 创建 .ssh 目录并设置权限
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # 写入私钥并设置权限
          echo "${DEPLOY_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 添加 GitHub 到 known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          cd public
          git init
          git remote add origin git@github.com:biuaxia/blog_20241113.git
          git checkout -b $GIT_DEPLOY_BRANCH
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin $GIT_DEPLOY_BRANCH
